### ISSUE TITLE
Labels e Milestones

### ISSUE THREAD

**Issue by iagocarrazzoni** [iagoggcarrazzoni/ex17-AFNDtoAFDtoERtoAFND#1]
Pessoal, peço ajuda para a criação dos Labels e das Milestones.

**Comment by iagocarrazzoni** [comment]
Criei alguns Labels, por favor olhem se está tudo ok

**Comment by dudecd3** [comment]
Acho que as labels estão suficientes.

**Comment by dudecd3** [comment]
Quanto às milestones, creio que precisaremos de quatro: uma para a adição do código, uma para correção de bugs, uma para sincronização das partes, uma para correção de bugs e a versão final.
