### ISSUE TITLE
Organização do trabalho

### ISSUE THREAD

**Issue by iagocarrazzoni** [iagoggcarrazzoni/ex17-AFNDtoAFDtoERtoAFND#2]
Pessoal, precisamos organizar o programa, dividir os trabalhos. Acho uma boa ideia formarmos pequenos núcleos responsáveis por cada parte (ex11, ex12 e ex16), pois acho que fica mais rápido, mas todo mundo sempre se ajudando. Peço, por favor, que digam suas ideias.

**Comment by dudecd3** [comment]
Gostei da ideia, @iagoggcarrazzoni . Como podemos fazer essa divisão, pessoal?

**Comment by ViniciusAraujoGR** [comment]
Acredito que eu, @Ewertongsantos e Caio podemos ficar encarregados de colocar o 11 no programa.

**Comment by yasmim13** [comment]
Posso ficar com a parte do ex16.

**Comment by adroutos** [comment]
Posso ficar  com parte do 12!

**Comment by Brenda100** [comment]
Ótima ideia! Posso me juntar ao 12 também.

**Comment by dudecd3** [comment]
Vou ficar com o pessoal do 12 então.

**Comment by LuccaMacielM** [comment]
Me junto ao pessoal do ex11

**Comment by lucas-sena** [comment]
Pra fechar então, vou ficar com o 12 tbm.
